name: Weekly book build
on:
  schedule:
    # minute[0,59], hour[0,23], day[1,31], month[1,12], weekday[0,6]
    - cron: '* 0 * * 1' # every monday at 0000
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          VERCEL_BUILD_HOOK: ${{ secrets.VERCEL_BUILD_HOOK }}
        run: |
          curl -X POST "$VERCEL_BUILD_HOOK"
